# Generated by Django 2.0.6 on 2018-06-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_article_wordcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='desc',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
