# Generated by Django 2.0.6 on 2018-06-25 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSO', '0005_auto_20180621_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='words',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
