# Generated by Django 2.0.6 on 2018-06-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSO', '0006_user_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='words',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
